### ISSUE TITLE
Update doesnt work well - 404 Not found

### ISSUE THREAD

**Issue by daeks** [TechieGuy12/PlexServerAutoUpdater#8] opened 2017-07-13 05:40 UTC
Doing an update results in a "404 Not Found" at the end. It also looks like that not all processes are killed correctly.

**Comment by TechieGuy12** [comment] 2017-07-13 11:58
Can you send a screenshot of the 404 Not Found message?

**Comment by daeks** [comment] 2017-07-14 07:43
Sure, I will try it on the next plex update.

**Comment by aaronchi** [comment] 2017-07-14 14:32
I have this issue as well. Even after running the updater manually, I have to restart the PlexService service for the server to actually update.

**Comment by daeks** [comment] 2017-07-31 14:12
see latest update.

before:
![before upgrade](https://user-images.githubusercontent.com/3989440/28781591-e3cf589e-760a-11e7-9977-9c7fa954d3d8.PNG)
psupdate.exe:
![upgrade](https://user-images.githubusercontent.com/3989440/28781595-e6cdb84c-760a-11e7-97ac-5b9d36d33710.PNG)

after:
![after upgrade](https://user-images.githubusercontent.com/3989440/28781600-e9724c52-760a-11e7-90d4-166b79840442.PNG)
![plex](https://user-images.githubusercontent.com/3989440/28781621-ee484ef2-760a-11e7-81b1-a43f226e1c1e.PNG)

**Comment by TechieGuy12** [comment] 2017-08-10 16:50
I can't seem to reproduce the error on my side.  So if you stop the service and restart it, then it works again? It does seem to update - at least according to your screenshot, but for some reason it can't find the Web server.

**Comment by daeks** [comment] 2017-08-10 17:45
Well, if you look on the PID it looks more like that the original process does not killed properly. The PID of Plex Media Server is before and after the update 5504.

**Comment by TechieGuy12** [comment] 2017-08-10 19:17
It appears so.  I'll look into it. Is the ID of the Plex Media Server process the same or different than the on that runs the Plex Service?

**Comment by daeks** [comment] 2017-08-11 05:06
Looking on the screenshot above plexservice has 2384 (before) and 6224 (after)

**Comment by TechieGuy12** [comment] 2017-08-14 16:31
Sorry, I meant the user ID.  Since the Plex Media Server wasn't shutdown during the upgrade, then I have missed something with regards to the user context it is running under.  Which account is the Plex Media Server running under?

**Comment by daeks** [comment] 2017-08-15 19:09
it runs as local account with administrative rights. I am using the same server for Plex as well as for the update script

**Comment by TechieGuy12** [comment] 2017-08-16 22:35
Is it the same admin account that executes the update? 

_Sent from my Samsung SM-N910W8 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by daeks** [comment] 2017-08-17 08:39
as mentioned above, yes :)

**Comment by daeks** [comment] 2017-09-05 15:03
@TechieGuy12 anything new about that issue? Plex is trowing with updates and I want to use it again :)

**Comment by TechieGuy12** [comment] 2017-09-05 15:42
I'll post an update in the develop branch soon so you can try the update.

**Comment by TechieGuy12** [comment] 2017-09-06 00:10
Can you try the pre-release version 0.1.5.2?

**Comment by daeks** [comment] 2017-09-06 08:01
Where can I find the binary?

**Comment by TechieGuy12** [comment] 2017-09-06 22:56
I have updated to version 0.1.5.3 to fix a bug I found.  The binaries should available for that release.

**Comment by daeks** [comment] 2017-09-07 06:40
I tried 0.1.5.3 but still the same issue:

before:
![image](https://user-images.githubusercontent.com/3989440/30149441-ea517c64-93a7-11e7-9a24-94c39e97da94.png)

![image](https://user-images.githubusercontent.com/3989440/30149492-1858cf40-93a8-11e7-87ec-008a6e697a24.png)

Log: https://pastebin.com/raw/Li3PkErN

after:
![image](https://user-images.githubusercontent.com/3989440/30149452-f53e4c38-93a7-11e7-9e4e-99b7aafd0bb2.png)
![image](https://user-images.githubusercontent.com/3989440/30149470-09ef373c-93a8-11e7-991b-f871c00f63f0.png)

**Comment by TechieGuy12** [comment] 2017-09-07 20:49
The issue appears to be that when the plex service is stopped the plex media server process isn't stopped. I'll release a new build and see if that fixes the issue.

**Comment by TechieGuy12** [comment] 2017-09-07 22:41
I have included the additional Plex processes that should have been stopped when the service stopped to the list of processes that is manually stopped before the update.  Release 0.1.5.4 has this change.

**Comment by aaronchi** [comment] 2017-09-07 22:47
0.1.5.4 worked for me 👍

**Comment by TechieGuy12** [comment] 2017-09-08 01:56
@aaronchi That is good to hear.

**Comment by daeks** [comment] 2017-09-08 10:44
It looks like that it worked but for any reason it ends with "unable to start plex service". After restarting the plex service manually, Plex worked again. I will try it again on the next update to confirm that the issue is solved.

**Comment by TechieGuy12** [comment] 2017-09-08 19:06
The updater creates a log file  - %temp%\plex-updater.txt. This may have an exception associated with the plex service not restarting.  If you can attach it to a reply, I can have a look and debug that issue.

**Comment by daeks** [comment] 2017-09-09 09:03
Unfortunately it was overwritten as I restarted the psupdate.exe :( I will post and retry on next Plex update

**Comment by daeks** [comment] 2017-09-14 15:56
With the latest plex update I can also confirm the restart of the service. From my side, the issue could be closed.

**Comment by TechieGuy12** [comment] 2017-09-14 19:27
No problem.  I will close the issue.

**Closed by TechieGuy12** 2017-09-14 19:27 UTC

**Comment by reloxx13** [comment] 2022-07-24 07:36
This is issue is back, when i trigger the update manual over the plex ui, ill end in a 404. After a restart of the plex service its up again.
