### ISSUE TITLE
object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jpsoutlook** [TechieGuy12/PlexServerAutoUpdater#7] opened 2017-06-12 19:48 UTC
Hi, I have plex as a service installed on WHS2011.  I just had to replace my system drive so this is a fresh install of WHS2011.  When I try to execute as admin psupdate.exe throw up this error.

object reference not set to an instance of an object

**Comment by TechieGuy12** [comment] 2017-06-12 22:18
Hi, Do you have .Net framework 3.5 installed? A previous issue was resolved by installing .Net 3.5.

**Comment by jpsoutlook** [comment] 2017-06-12 23:11
yes 3.5.1

![image](https://user-images.githubusercontent.com/21351204/27059142-d48a74c4-4f89-11e7-9171-3df6da005a89.png)

**Comment by TechieGuy12** [comment] 2017-06-12 23:35
An I just checked the project and it was set for .Net 4.0. How are you running the updater - with the GUI or silently?

**Comment by jpsoutlook** [comment] 2017-06-12 23:49
right click run as admin have not gotten far enough to schedule it

**Comment by TechieGuy12** [comment] 2017-06-12 23:51
Sorry, I updated my last comment.  Do you have .Net 4.0 also installed?  That is the target framework, however, some assemblies are from .Net 3.5.

**Comment by jpsoutlook** [comment] 2017-06-13 00:00
![image](https://user-images.githubusercontent.com/21351204/27060305-ae6c43c4-4f90-11e7-8eb9-5fd77a962b47.png)

**Comment by jpsoutlook** [comment] 2017-06-13 00:02
![image](https://user-images.githubusercontent.com/21351204/27060340-f4e1dd46-4f90-11e7-9cf2-ef6556aa8c8f.png)

**Comment by jpsoutlook** [comment] 2017-06-13 00:03
not sure whats up since this is a new clean install of whs2011 with all updates on a ssd

**Comment by TechieGuy12** [comment] 2017-06-13 00:31
I have updated the develop branch. There is a zip file that contains the compiled develop branch version. Can you try to run that one to see if there is more to the error message?

**Comment by jpsoutlook** [comment] 2017-06-13 02:01
i get the same error

**Comment by jpsoutlook** [comment] 2017-06-13 02:17
![image](https://user-images.githubusercontent.com/21351204/27062991-d0acc482-4fa3-11e7-9f68-f49626bff565.png)

**Comment by jpsoutlook** [comment] 2017-06-13 02:18
![image](https://user-images.githubusercontent.com/21351204/27063003-e323fa4a-4fa3-11e7-905a-58c258a9a6c4.png)

**Comment by TechieGuy12** [comment] 2017-06-13 22:46
Can you download the psupdate.zip file from the develop branch and then run the psupdate.exe from a command window?

**Comment by jpsoutlook** [comment] 2017-06-14 00:09
I get the same error running as admin via cmd, cmd silent 

![image](https://user-images.githubusercontent.com/21351204/27109996-11164608-505b-11e7-8e58-7987b0333c46.png)

**Comment by TechieGuy12** [comment] 2017-06-14 00:29
Sorry, my bad.  Because it is a Windows application, it couldn't write to the command window.  I have updated the psupdate.zip file with a version that can now output to the command window.

**Comment by jpsoutlook** [comment] 2017-06-14 03:41
results of silent command and the pop up error is when you just right click run as admin

![image](https://user-images.githubusercontent.com/21351204/27114460-af8c86c2-5078-11e7-8218-49e66c58db21.png)

**Comment by TechieGuy12** [comment] 2017-06-16 01:16
Thanks for the screenshot. That helps. I have updated the develop branch again for more additional information.  Can you try running it again?  There should be more information displayed in the message box.

**Comment by jpsoutlook** [comment] 2017-06-16 16:41
When I run it in command line it just sits at Initializing a silent update, when run as normal/admin I get a new error with more information.

![image](https://user-images.githubusercontent.com/21351204/27236004-ff9f6ad4-5277-11e7-93be-d24788bc5608.png)

**Comment by jpsoutlook** [comment] 2017-06-16 16:46
My server is an HP EX495 with upgraded cpu and ram.  Fresh install with all updates WHS 2011, drive bender drive pool.  C:/ is isolated from the pool, this is where PMS is installed.  No part of C:/ is in the drivepool.  C:/ is an SSD.  Here is a list of what is installed on my server.

![image](https://user-images.githubusercontent.com/21351204/27236129-78a4d0ea-5278-11e7-9314-0bfc8fa1f11e.png)

![image](https://user-images.githubusercontent.com/21351204/27236161-a8aa66a6-5278-11e7-8b8d-c81e73540761.png)

**Comment by TechieGuy12** [comment] 2017-06-16 17:40
Ah, I think I know what the issue is.  Since it is a fresh install, there have been no updates downloaded, so no previous updates exist for your installation of Plex.  I have tracked down the line that causes the exception, and I will look at fixing the problem - which pretty much just indicates that there are no update folders at this time. 

Can you confirm that the %LocalAppData%\Plex Media Server\Updates folder is empty?

**Comment by jpsoutlook** [comment] 2017-06-16 18:04
Boom!  I think you solved it.  There is not update folder as it has not been created as of yet. 

![image](https://user-images.githubusercontent.com/21351204/27238912-9b30949a-5283-11e7-8b05-5d501f0393e6.png)

**Comment by TechieGuy12** [comment] 2017-06-16 19:18
The good news is that once an update has been downloaded, the updater should work. I will now need to update the code to handle this scenario and also include additional logging to make future debugging much easier.

**Comment by TechieGuy12** [comment] 2017-06-17 02:37
A new release - 0.1.4.0 - has been published to fix the error.  Download it and see if you no longer receive the error.

**Comment by jpsoutlook** [comment] 2017-06-18 03:49
this just means there is not update correct?

![image](https://user-images.githubusercontent.com/21351204/27257916-78b57496-539e-11e7-9dad-df681e9975c9.png)

**Comment by TechieGuy12** [comment] 2017-06-18 12:28
That is correct.  I'll default the value of the latest version, if no update exists, to the same as the current version to make it more clear.

**Comment by TechieGuy12** [comment] 2017-06-18 12:54
The change has been made.  Although, I do see a new update has just downloaded to my server, so you may have the updates folder created soon, if it hasn't already.

**Closed** 2017-06-20 12:30 UTC
